name: All Packages Release

env:
  OUTPUT: ./Output
  CONFIG: Release

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:      
    - uses: actions/checkout@v2  
      
    - name: Setup .net core
      uses: actions/setup-dotnet@v1.4.0
      
    - name: Restore dependencies
      run: dotnet restore ./src/SeoToolkit.Umbraco.sln

    - name: Build
      run: dotnet build ./src/SeoToolkit.Umbraco.sln --configuration ${{ env.CONFIG }} --no-restore

    - name: Create NuGet packages
      run: dotnet pack ./src/SeoToolkit.Umbraco.sln -c ${{ env.CONFIG }} --no-build
      
    - name: Copy files
      run: find . -name ".nupkg" -type f ./Output

#    - name: Push packages to NuGet
#      run: dotnet nuget push "**/*.nupkg" -k ${{ secrets.NUGET_DEPLOY_KEY }} -s https://api.nuget.org/v3/index.json

    - name: upload-artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Build-Results
        path: ${{ env.OUTPUT }}/**/*
